export * from './Genres';
export * from './Header';
export * from './MovieInfo';
export * from './MoviesListCards';
export * from './MoviesListCard';
export * from './MoviePagination';
export * from './SearchMovie';
export * from './StarsRating'
export * from './SearchMovieForm'
