export * from './Genres';
export * from './Header';
export * from './MovieInfo';
export * from './MoviesListCards';
export * from './MoviesListCard';
export * from './MoviePagination';
export * from './SearchMovies';
export * from './StarsRating'
export * from './SearchMovieForm'
export * from './ButtonBack';
export * from './Switcher';